---
- name: DFG | Download | Create local tmp dir
  file: state=directory recurse=yes path={{ dfg_download_tmp }}
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no

- name: DFG | Download | Create local build dir
  file: state=directory recurse=yes path={{ dfg_build_to }}
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no
  
# http basic auth is unhappy with get_url, not sure why
- name: DFG | Download | Download archive
  get_url:
    url: "{{ dfg_deploy_from }}"
    dest: "{{ dfg_download_tmp }}/{{ dfg_github_repo | replace('/','-') }}-{{ dfg_release_version }}.tar.gz"
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no

- name: DFG | Download | Clean local build dir
  shell: "rm -rf {{ dfg_build_to }}/*"
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no

- name: DFG | Download | Extract archive
  command: "tar xzf {{ dfg_download_tmp }}/{{ dfg_github_repo |  replace('/','-') }}-{{ dfg_release_version }}.tar.gz --strip-components={{ dfg_strip_dirs }} -C {{ dfg_build_to }}"
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no
