---
- name: DFG | Git | Create local build dir
  file: state=directory recurse=yes path={{ dfg_build_to }}
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no

- name: DFG | Git | Clean local build dir
  shell: "rm -rf {{ dfg_build_to }}/*"
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no
 
- name: DFG | Git | Git clone
  git:
   repo: "{{ dfg_deploy_from }}"
   dest: "{{ dfg_build_to }}"
   depth: 1
   accept_hostkey: yes
   force: yes
   refspec: "{{ dfg_release_version }}"
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no

- name: DFG | Git | Create .release file
  template:  src=release.j2 dest={{ dfg_build_to }}/.release
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no
