---
- name: DFG | Git | Create local build dir
  file: state=directory recurse=yes path={{ dfg_build_to }}
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no

- name: DFG | Git | Clean local build dir
  shell: "find {{ dfg_build_to }}/ -delete"
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no
 
- name: DFG | Git | Git clone
  git:
   repo: "{{ dfg_deploy_from }}"
   dest: "{{ dfg_build_to }}"
   accept_hostkey: yes
   force: yes
   version: "{{ dfg_release_version }}"
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no

