---
# Clean up releases
- name: DFG | Prune old releases
  shell: ls -1dt "{{ dfg_deploy_to }}/{{ dfg_version_dir }}" | tail -n +$(({{ dfg_keep_releases }} + 1)) | xargs rm -rf
  when: dfg_keep_releases > 0
