---
# Setup folders
- name: DFG | Ensure deployment base path exists
  file: state=directory recurse=yes path={{ dfg_deploy_to }}

- name: DFG | Ensure releases folder exists
  file: state=directory recurse=yes path={{ dfg_deploy_to }}/{{ dfg_version_dir }}

- name: DFG | Ensure shared elements folder exists
  file: state=directory recurse=yes path={{ dfg_deploy_to }}/shared
